import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ReduxProvider } from "./configs/redux-provider";
import Script from "next/script";
import WhatsAppIcon from "./components/WhatsappIcon";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // ✅ Add weights you plan to use
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ReduxProvider>
          <Header />
          {children}
          <WhatsAppIcon />
        </ReduxProvider>
        <Script src="https://js.paystack.co/v1/inline.js" strategy="afterInteractive" />
        <Footer />
      </body>
    </html>
  );
}
